#!/bin/sh

set -eux 
set -o pipefail

get_resource_version() {
  jq -n "{
      source: {
         api_token: \"${1}\",
         resource_name: \"${2}\"
      },
      version: {}
    }" | "${resource_dir}/check" | jq -r '.[0].version'
}

main() {
  resource_dir="/opt/resource"

  version=$(get_resource_version token p-gitlab)
  test "${version}" = "0.1.1 BETA"

  version=$(get_resource_version token p-mysql)
  test "${version}" = "1.7.1.0"
}

if [ "$(basename "${0}")" = "all" ]; then
  main
fi
