#!/bin/bash

set -eux

my_dir="$( cd "$( dirname "${0}" )" && pwd )"
base_dir="$( cd "${my_dir}/../.." && pwd )"
scripts_dir="$( cd "${base_dir}/scripts" && pwd )"

export S3_OUT_LOCATION="${PWD}/s3-out-binary/s3-out"
export GOPATH="${PWD}/gopath"
export PATH="${GOPATH}/bin:${PATH}"

go get github.com/onsi/ginkgo/ginkgo
go get github.com/tools/godep

pushd "${base_dir}" > /dev/null
  godep restore
popd > /dev/null

"${scripts_dir}/test" "$@"
