// Code generated by counterfeiter. DO NOT EDIT.
package infakes

import (
	"sync"

	"github.com/pivotal-cf/pivnet-resource/v3/metadata"
)

type FakeFileWriter struct {
	WriteMetadataJSONFileStub        func(metadata.Metadata) error
	writeMetadataJSONFileMutex       sync.RWMutex
	writeMetadataJSONFileArgsForCall []struct {
		arg1 metadata.Metadata
	}
	writeMetadataJSONFileReturns struct {
		result1 error
	}
	writeMetadataJSONFileReturnsOnCall map[int]struct {
		result1 error
	}
	WriteMetadataYAMLFileStub        func(metadata.Metadata) error
	writeMetadataYAMLFileMutex       sync.RWMutex
	writeMetadataYAMLFileArgsForCall []struct {
		arg1 metadata.Metadata
	}
	writeMetadataYAMLFileReturns struct {
		result1 error
	}
	writeMetadataYAMLFileReturnsOnCall map[int]struct {
		result1 error
	}
	WriteVersionFileStub        func(string) error
	writeVersionFileMutex       sync.RWMutex
	writeVersionFileArgsForCall []struct {
		arg1 string
	}
	writeVersionFileReturns struct {
		result1 error
	}
	writeVersionFileReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeFileWriter) WriteMetadataJSONFile(arg1 metadata.Metadata) error {
	fake.writeMetadataJSONFileMutex.Lock()
	ret, specificReturn := fake.writeMetadataJSONFileReturnsOnCall[len(fake.writeMetadataJSONFileArgsForCall)]
	fake.writeMetadataJSONFileArgsForCall = append(fake.writeMetadataJSONFileArgsForCall, struct {
		arg1 metadata.Metadata
	}{arg1})
	stub := fake.WriteMetadataJSONFileStub
	fakeReturns := fake.writeMetadataJSONFileReturns
	fake.recordInvocation("WriteMetadataJSONFile", []interface{}{arg1})
	fake.writeMetadataJSONFileMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeFileWriter) WriteMetadataJSONFileCallCount() int {
	fake.writeMetadataJSONFileMutex.RLock()
	defer fake.writeMetadataJSONFileMutex.RUnlock()
	return len(fake.writeMetadataJSONFileArgsForCall)
}

func (fake *FakeFileWriter) WriteMetadataJSONFileCalls(stub func(metadata.Metadata) error) {
	fake.writeMetadataJSONFileMutex.Lock()
	defer fake.writeMetadataJSONFileMutex.Unlock()
	fake.WriteMetadataJSONFileStub = stub
}

func (fake *FakeFileWriter) WriteMetadataJSONFileArgsForCall(i int) metadata.Metadata {
	fake.writeMetadataJSONFileMutex.RLock()
	defer fake.writeMetadataJSONFileMutex.RUnlock()
	argsForCall := fake.writeMetadataJSONFileArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeFileWriter) WriteMetadataJSONFileReturns(result1 error) {
	fake.writeMetadataJSONFileMutex.Lock()
	defer fake.writeMetadataJSONFileMutex.Unlock()
	fake.WriteMetadataJSONFileStub = nil
	fake.writeMetadataJSONFileReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeFileWriter) WriteMetadataJSONFileReturnsOnCall(i int, result1 error) {
	fake.writeMetadataJSONFileMutex.Lock()
	defer fake.writeMetadataJSONFileMutex.Unlock()
	fake.WriteMetadataJSONFileStub = nil
	if fake.writeMetadataJSONFileReturnsOnCall == nil {
		fake.writeMetadataJSONFileReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.writeMetadataJSONFileReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeFileWriter) WriteMetadataYAMLFile(arg1 metadata.Metadata) error {
	fake.writeMetadataYAMLFileMutex.Lock()
	ret, specificReturn := fake.writeMetadataYAMLFileReturnsOnCall[len(fake.writeMetadataYAMLFileArgsForCall)]
	fake.writeMetadataYAMLFileArgsForCall = append(fake.writeMetadataYAMLFileArgsForCall, struct {
		arg1 metadata.Metadata
	}{arg1})
	stub := fake.WriteMetadataYAMLFileStub
	fakeReturns := fake.writeMetadataYAMLFileReturns
	fake.recordInvocation("WriteMetadataYAMLFile", []interface{}{arg1})
	fake.writeMetadataYAMLFileMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeFileWriter) WriteMetadataYAMLFileCallCount() int {
	fake.writeMetadataYAMLFileMutex.RLock()
	defer fake.writeMetadataYAMLFileMutex.RUnlock()
	return len(fake.writeMetadataYAMLFileArgsForCall)
}

func (fake *FakeFileWriter) WriteMetadataYAMLFileCalls(stub func(metadata.Metadata) error) {
	fake.writeMetadataYAMLFileMutex.Lock()
	defer fake.writeMetadataYAMLFileMutex.Unlock()
	fake.WriteMetadataYAMLFileStub = stub
}

func (fake *FakeFileWriter) WriteMetadataYAMLFileArgsForCall(i int) metadata.Metadata {
	fake.writeMetadataYAMLFileMutex.RLock()
	defer fake.writeMetadataYAMLFileMutex.RUnlock()
	argsForCall := fake.writeMetadataYAMLFileArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeFileWriter) WriteMetadataYAMLFileReturns(result1 error) {
	fake.writeMetadataYAMLFileMutex.Lock()
	defer fake.writeMetadataYAMLFileMutex.Unlock()
	fake.WriteMetadataYAMLFileStub = nil
	fake.writeMetadataYAMLFileReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeFileWriter) WriteMetadataYAMLFileReturnsOnCall(i int, result1 error) {
	fake.writeMetadataYAMLFileMutex.Lock()
	defer fake.writeMetadataYAMLFileMutex.Unlock()
	fake.WriteMetadataYAMLFileStub = nil
	if fake.writeMetadataYAMLFileReturnsOnCall == nil {
		fake.writeMetadataYAMLFileReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.writeMetadataYAMLFileReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeFileWriter) WriteVersionFile(arg1 string) error {
	fake.writeVersionFileMutex.Lock()
	ret, specificReturn := fake.writeVersionFileReturnsOnCall[len(fake.writeVersionFileArgsForCall)]
	fake.writeVersionFileArgsForCall = append(fake.writeVersionFileArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.WriteVersionFileStub
	fakeReturns := fake.writeVersionFileReturns
	fake.recordInvocation("WriteVersionFile", []interface{}{arg1})
	fake.writeVersionFileMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeFileWriter) WriteVersionFileCallCount() int {
	fake.writeVersionFileMutex.RLock()
	defer fake.writeVersionFileMutex.RUnlock()
	return len(fake.writeVersionFileArgsForCall)
}

func (fake *FakeFileWriter) WriteVersionFileCalls(stub func(string) error) {
	fake.writeVersionFileMutex.Lock()
	defer fake.writeVersionFileMutex.Unlock()
	fake.WriteVersionFileStub = stub
}

func (fake *FakeFileWriter) WriteVersionFileArgsForCall(i int) string {
	fake.writeVersionFileMutex.RLock()
	defer fake.writeVersionFileMutex.RUnlock()
	argsForCall := fake.writeVersionFileArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeFileWriter) WriteVersionFileReturns(result1 error) {
	fake.writeVersionFileMutex.Lock()
	defer fake.writeVersionFileMutex.Unlock()
	fake.WriteVersionFileStub = nil
	fake.writeVersionFileReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeFileWriter) WriteVersionFileReturnsOnCall(i int, result1 error) {
	fake.writeVersionFileMutex.Lock()
	defer fake.writeVersionFileMutex.Unlock()
	fake.WriteVersionFileStub = nil
	if fake.writeVersionFileReturnsOnCall == nil {
		fake.writeVersionFileReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.writeVersionFileReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeFileWriter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.writeMetadataJSONFileMutex.RLock()
	defer fake.writeMetadataJSONFileMutex.RUnlock()
	fake.writeMetadataYAMLFileMutex.RLock()
	defer fake.writeMetadataYAMLFileMutex.RUnlock()
	fake.writeVersionFileMutex.RLock()
	defer fake.writeVersionFileMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeFileWriter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
