// This file was generated by counterfeiter
package infakes

import (
	"sync"

	"github.com/pivotal-cf-experimental/pivnet-resource/in"
	"github.com/pivotal-cf-experimental/pivnet-resource/metadata"
)

type FakeFileWriter struct {
	WriteMetadataJSONFileStub        func(mdata metadata.Metadata) error
	writeMetadataJSONFileMutex       sync.RWMutex
	writeMetadataJSONFileArgsForCall []struct {
		mdata metadata.Metadata
	}
	writeMetadataJSONFileReturns struct {
		result1 error
	}
	WriteMetadataYAMLFileStub        func(mdata metadata.Metadata) error
	writeMetadataYAMLFileMutex       sync.RWMutex
	writeMetadataYAMLFileArgsForCall []struct {
		mdata metadata.Metadata
	}
	writeMetadataYAMLFileReturns struct {
		result1 error
	}
	WriteVersionFileStub        func(versionWithETag string) error
	writeVersionFileMutex       sync.RWMutex
	writeVersionFileArgsForCall []struct {
		versionWithETag string
	}
	writeVersionFileReturns struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeFileWriter) WriteMetadataJSONFile(mdata metadata.Metadata) error {
	fake.writeMetadataJSONFileMutex.Lock()
	fake.writeMetadataJSONFileArgsForCall = append(fake.writeMetadataJSONFileArgsForCall, struct {
		mdata metadata.Metadata
	}{mdata})
	fake.recordInvocation("WriteMetadataJSONFile", []interface{}{mdata})
	fake.writeMetadataJSONFileMutex.Unlock()
	if fake.WriteMetadataJSONFileStub != nil {
		return fake.WriteMetadataJSONFileStub(mdata)
	} else {
		return fake.writeMetadataJSONFileReturns.result1
	}
}

func (fake *FakeFileWriter) WriteMetadataJSONFileCallCount() int {
	fake.writeMetadataJSONFileMutex.RLock()
	defer fake.writeMetadataJSONFileMutex.RUnlock()
	return len(fake.writeMetadataJSONFileArgsForCall)
}

func (fake *FakeFileWriter) WriteMetadataJSONFileArgsForCall(i int) metadata.Metadata {
	fake.writeMetadataJSONFileMutex.RLock()
	defer fake.writeMetadataJSONFileMutex.RUnlock()
	return fake.writeMetadataJSONFileArgsForCall[i].mdata
}

func (fake *FakeFileWriter) WriteMetadataJSONFileReturns(result1 error) {
	fake.WriteMetadataJSONFileStub = nil
	fake.writeMetadataJSONFileReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeFileWriter) WriteMetadataYAMLFile(mdata metadata.Metadata) error {
	fake.writeMetadataYAMLFileMutex.Lock()
	fake.writeMetadataYAMLFileArgsForCall = append(fake.writeMetadataYAMLFileArgsForCall, struct {
		mdata metadata.Metadata
	}{mdata})
	fake.recordInvocation("WriteMetadataYAMLFile", []interface{}{mdata})
	fake.writeMetadataYAMLFileMutex.Unlock()
	if fake.WriteMetadataYAMLFileStub != nil {
		return fake.WriteMetadataYAMLFileStub(mdata)
	} else {
		return fake.writeMetadataYAMLFileReturns.result1
	}
}

func (fake *FakeFileWriter) WriteMetadataYAMLFileCallCount() int {
	fake.writeMetadataYAMLFileMutex.RLock()
	defer fake.writeMetadataYAMLFileMutex.RUnlock()
	return len(fake.writeMetadataYAMLFileArgsForCall)
}

func (fake *FakeFileWriter) WriteMetadataYAMLFileArgsForCall(i int) metadata.Metadata {
	fake.writeMetadataYAMLFileMutex.RLock()
	defer fake.writeMetadataYAMLFileMutex.RUnlock()
	return fake.writeMetadataYAMLFileArgsForCall[i].mdata
}

func (fake *FakeFileWriter) WriteMetadataYAMLFileReturns(result1 error) {
	fake.WriteMetadataYAMLFileStub = nil
	fake.writeMetadataYAMLFileReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeFileWriter) WriteVersionFile(versionWithETag string) error {
	fake.writeVersionFileMutex.Lock()
	fake.writeVersionFileArgsForCall = append(fake.writeVersionFileArgsForCall, struct {
		versionWithETag string
	}{versionWithETag})
	fake.recordInvocation("WriteVersionFile", []interface{}{versionWithETag})
	fake.writeVersionFileMutex.Unlock()
	if fake.WriteVersionFileStub != nil {
		return fake.WriteVersionFileStub(versionWithETag)
	} else {
		return fake.writeVersionFileReturns.result1
	}
}

func (fake *FakeFileWriter) WriteVersionFileCallCount() int {
	fake.writeVersionFileMutex.RLock()
	defer fake.writeVersionFileMutex.RUnlock()
	return len(fake.writeVersionFileArgsForCall)
}

func (fake *FakeFileWriter) WriteVersionFileArgsForCall(i int) string {
	fake.writeVersionFileMutex.RLock()
	defer fake.writeVersionFileMutex.RUnlock()
	return fake.writeVersionFileArgsForCall[i].versionWithETag
}

func (fake *FakeFileWriter) WriteVersionFileReturns(result1 error) {
	fake.WriteVersionFileStub = nil
	fake.writeVersionFileReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeFileWriter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.writeMetadataJSONFileMutex.RLock()
	defer fake.writeMetadataJSONFileMutex.RUnlock()
	fake.writeMetadataYAMLFileMutex.RLock()
	defer fake.writeMetadataYAMLFileMutex.RUnlock()
	fake.writeVersionFileMutex.RLock()
	defer fake.writeVersionFileMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeFileWriter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ in.FileWriter = new(FakeFileWriter)
