// This file was generated by counterfeiter
package infakes

import (
	"sync"

	"github.com/pivotal-cf-experimental/pivnet-resource/in"
)

type FakeFileSummer struct {
	SumFileStub        func(filepath string) (string, error)
	sumFileMutex       sync.RWMutex
	sumFileArgsForCall []struct {
		filepath string
	}
	sumFileReturns struct {
		result1 string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeFileSummer) SumFile(filepath string) (string, error) {
	fake.sumFileMutex.Lock()
	fake.sumFileArgsForCall = append(fake.sumFileArgsForCall, struct {
		filepath string
	}{filepath})
	fake.recordInvocation("SumFile", []interface{}{filepath})
	fake.sumFileMutex.Unlock()
	if fake.SumFileStub != nil {
		return fake.SumFileStub(filepath)
	} else {
		return fake.sumFileReturns.result1, fake.sumFileReturns.result2
	}
}

func (fake *FakeFileSummer) SumFileCallCount() int {
	fake.sumFileMutex.RLock()
	defer fake.sumFileMutex.RUnlock()
	return len(fake.sumFileArgsForCall)
}

func (fake *FakeFileSummer) SumFileArgsForCall(i int) string {
	fake.sumFileMutex.RLock()
	defer fake.sumFileMutex.RUnlock()
	return fake.sumFileArgsForCall[i].filepath
}

func (fake *FakeFileSummer) SumFileReturns(result1 string, result2 error) {
	fake.SumFileStub = nil
	fake.sumFileReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeFileSummer) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.sumFileMutex.RLock()
	defer fake.sumFileMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeFileSummer) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ in.FileSummer = new(FakeFileSummer)
