// This file was generated by counterfeiter
package infakes

import (
	"sync"

	"github.com/pivotal-cf-experimental/pivnet-resource/in"
)

type FakeDownloader struct {
	DownloadStub        func(downloadLinks map[string]string) ([]string, error)
	downloadMutex       sync.RWMutex
	downloadArgsForCall []struct {
		downloadLinks map[string]string
	}
	downloadReturns struct {
		result1 []string
		result2 error
	}
	invocations map[string][][]interface{}
}

func (fake *FakeDownloader) Download(downloadLinks map[string]string) ([]string, error) {
	fake.downloadMutex.Lock()
	fake.downloadArgsForCall = append(fake.downloadArgsForCall, struct {
		downloadLinks map[string]string
	}{downloadLinks})
	fake.guard("Download")
	fake.invocations["Download"] = append(fake.invocations["Download"], []interface{}{downloadLinks})
	fake.downloadMutex.Unlock()
	if fake.DownloadStub != nil {
		return fake.DownloadStub(downloadLinks)
	} else {
		return fake.downloadReturns.result1, fake.downloadReturns.result2
	}
}

func (fake *FakeDownloader) DownloadCallCount() int {
	fake.downloadMutex.RLock()
	defer fake.downloadMutex.RUnlock()
	return len(fake.downloadArgsForCall)
}

func (fake *FakeDownloader) DownloadArgsForCall(i int) map[string]string {
	fake.downloadMutex.RLock()
	defer fake.downloadMutex.RUnlock()
	return fake.downloadArgsForCall[i].downloadLinks
}

func (fake *FakeDownloader) DownloadReturns(result1 []string, result2 error) {
	fake.DownloadStub = nil
	fake.downloadReturns = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakeDownloader) Invocations() map[string][][]interface{} {
	return fake.invocations
}

func (fake *FakeDownloader) guard(key string) {
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
}

var _ in.Downloader = new(FakeDownloader)
