#!/bin/bash

set -eux

my_dir="$( cd "$( dirname "${0}" )" && pwd )"
base_dir="$( cd "${my_dir}/../.." && pwd )"
s3_resource_dir="$( cd "${base_dir}/../../concourse/s3-resource" && pwd )"

export GOPATH=$PWD/gopath
export PATH=$GOPATH/bin:$PATH

go get github.com/onsi/ginkgo/ginkgo
go get github.com/onsi/gomega
go get github.com/golang/protobuf/proto # transitive dependency of gomega

pushd "${s3_resource_dir}" > /dev/null
  curl \
    -L \
    https://github.com/tools/godep/releases/download/v32/godep_linux_amd64 \
    > godep

  chmod +x ./godep
  ./godep restore

  ginkgo \
    -r \
    -p \
    -randomizeSuites \
    -randomizeAllSpecs \
    -v \
    .
popd > /dev/null
