// This file was generated by counterfeiter
package gpfakes

import (
	"sync"

	"github.com/pivotal-cf-experimental/pivnet-resource/gp"
)

type FakeExtendedClient struct {
	ReleaseETagStub        func(productSlug string, releaseID int) (string, error)
	releaseETagMutex       sync.RWMutex
	releaseETagArgsForCall []struct {
		productSlug string
		releaseID   int
	}
	releaseETagReturns struct {
		result1 string
		result2 error
	}
	invocations map[string][][]interface{}
}

func (fake *FakeExtendedClient) ReleaseETag(productSlug string, releaseID int) (string, error) {
	fake.releaseETagMutex.Lock()
	fake.releaseETagArgsForCall = append(fake.releaseETagArgsForCall, struct {
		productSlug string
		releaseID   int
	}{productSlug, releaseID})
	fake.guard("ReleaseETag")
	fake.invocations["ReleaseETag"] = append(fake.invocations["ReleaseETag"], []interface{}{productSlug, releaseID})
	fake.releaseETagMutex.Unlock()
	if fake.ReleaseETagStub != nil {
		return fake.ReleaseETagStub(productSlug, releaseID)
	} else {
		return fake.releaseETagReturns.result1, fake.releaseETagReturns.result2
	}
}

func (fake *FakeExtendedClient) ReleaseETagCallCount() int {
	fake.releaseETagMutex.RLock()
	defer fake.releaseETagMutex.RUnlock()
	return len(fake.releaseETagArgsForCall)
}

func (fake *FakeExtendedClient) ReleaseETagArgsForCall(i int) (string, int) {
	fake.releaseETagMutex.RLock()
	defer fake.releaseETagMutex.RUnlock()
	return fake.releaseETagArgsForCall[i].productSlug, fake.releaseETagArgsForCall[i].releaseID
}

func (fake *FakeExtendedClient) ReleaseETagReturns(result1 string, result2 error) {
	fake.ReleaseETagStub = nil
	fake.releaseETagReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeExtendedClient) Invocations() map[string][][]interface{} {
	return fake.invocations
}

func (fake *FakeExtendedClient) guard(key string) {
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
}

var _ gp.ExtendedClient = new(FakeExtendedClient)
