#!/bin/bash

set -eux

my_dir="$( cd "$( dirname "${0}" )" && pwd )"
base_dir="$( cd "${my_dir}/.." && pwd )"

pushd "${base_dir}" > /dev/null
  GOOS=linux go build -o check ./cmd/check
  GOOS=linux go build -o in ./cmd/in
  GOOS=linux go build -o out ./cmd/out
popd > /dev/null
