#!/bin/bash

set -eux

VERSION="${VERSION:-dev}"
GOOS="${GOOS:-linux}"

my_dir="$( cd "$( dirname "${0}" )" && pwd )"
base_dir="$( cd "${my_dir}/.." && pwd )"

pushd "${base_dir}" > /dev/null
  GOOS="${GOOS}" go build \
      -o "${base_dir}/cmd/check/check" \
      -ldflags "-X main.version=${VERSION}" \
      ./cmd/check
  GOOS="${GOOS}" go build \
      -o "${base_dir}/cmd/in/in" \
      -ldflags "-X main.version=${VERSION}" \
      ./cmd/in
  GOOS="${GOOS}" go build \
      -o "${base_dir}/cmd/out/out" \
      -ldflags "-X main.version=${VERSION}" \
      ./cmd/out
popd > /dev/null
