#!/bin/bash -eu

API_TOKEN="${API_TOKEN:?"API_TOKEN must be provided"}"

set -x

my_dir="$( cd "$( dirname "${0}" )" && pwd )"
base_dir="$( cd "${my_dir}/.." && pwd )"

pushd "${base_dir}" > /dev/null
  CGO_ENABLED=1 ginkgo \
    -r \
    -race \
    -p \
    -randomizeAllSpecs \
    -randomizeSuites \
    "$@"
popd > /dev/null
