// This file was generated by counterfeiter
package checkfakes

import (
	"sync"

	go_pivnet "github.com/pivotal-cf/go-pivnet"
)

type FakePivnetClient struct {
	ReleaseTypesStub        func() ([]go_pivnet.ReleaseType, error)
	releaseTypesMutex       sync.RWMutex
	releaseTypesArgsForCall []struct{}
	releaseTypesReturns     struct {
		result1 []go_pivnet.ReleaseType
		result2 error
	}
	ReleasesForProductSlugStub        func(string) ([]go_pivnet.Release, error)
	releasesForProductSlugMutex       sync.RWMutex
	releasesForProductSlugArgsForCall []struct {
		arg1 string
	}
	releasesForProductSlugReturns struct {
		result1 []go_pivnet.Release
		result2 error
	}
	ProductVersionsStub        func(productSlug string, releases []go_pivnet.Release) ([]string, error)
	productVersionsMutex       sync.RWMutex
	productVersionsArgsForCall []struct {
		productSlug string
		releases    []go_pivnet.Release
	}
	productVersionsReturns struct {
		result1 []string
		result2 error
	}
	ReleaseETagStub        func(productSlug string, releaseID int) (string, error)
	releaseETagMutex       sync.RWMutex
	releaseETagArgsForCall []struct {
		productSlug string
		releaseID   int
	}
	releaseETagReturns struct {
		result1 string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakePivnetClient) ReleaseTypes() ([]go_pivnet.ReleaseType, error) {
	fake.releaseTypesMutex.Lock()
	fake.releaseTypesArgsForCall = append(fake.releaseTypesArgsForCall, struct{}{})
	fake.recordInvocation("ReleaseTypes", []interface{}{})
	fake.releaseTypesMutex.Unlock()
	if fake.ReleaseTypesStub != nil {
		return fake.ReleaseTypesStub()
	} else {
		return fake.releaseTypesReturns.result1, fake.releaseTypesReturns.result2
	}
}

func (fake *FakePivnetClient) ReleaseTypesCallCount() int {
	fake.releaseTypesMutex.RLock()
	defer fake.releaseTypesMutex.RUnlock()
	return len(fake.releaseTypesArgsForCall)
}

func (fake *FakePivnetClient) ReleaseTypesReturns(result1 []go_pivnet.ReleaseType, result2 error) {
	fake.ReleaseTypesStub = nil
	fake.releaseTypesReturns = struct {
		result1 []go_pivnet.ReleaseType
		result2 error
	}{result1, result2}
}

func (fake *FakePivnetClient) ReleasesForProductSlug(arg1 string) ([]go_pivnet.Release, error) {
	fake.releasesForProductSlugMutex.Lock()
	fake.releasesForProductSlugArgsForCall = append(fake.releasesForProductSlugArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("ReleasesForProductSlug", []interface{}{arg1})
	fake.releasesForProductSlugMutex.Unlock()
	if fake.ReleasesForProductSlugStub != nil {
		return fake.ReleasesForProductSlugStub(arg1)
	} else {
		return fake.releasesForProductSlugReturns.result1, fake.releasesForProductSlugReturns.result2
	}
}

func (fake *FakePivnetClient) ReleasesForProductSlugCallCount() int {
	fake.releasesForProductSlugMutex.RLock()
	defer fake.releasesForProductSlugMutex.RUnlock()
	return len(fake.releasesForProductSlugArgsForCall)
}

func (fake *FakePivnetClient) ReleasesForProductSlugArgsForCall(i int) string {
	fake.releasesForProductSlugMutex.RLock()
	defer fake.releasesForProductSlugMutex.RUnlock()
	return fake.releasesForProductSlugArgsForCall[i].arg1
}

func (fake *FakePivnetClient) ReleasesForProductSlugReturns(result1 []go_pivnet.Release, result2 error) {
	fake.ReleasesForProductSlugStub = nil
	fake.releasesForProductSlugReturns = struct {
		result1 []go_pivnet.Release
		result2 error
	}{result1, result2}
}

func (fake *FakePivnetClient) ProductVersions(productSlug string, releases []go_pivnet.Release) ([]string, error) {
	var releasesCopy []go_pivnet.Release
	if releases != nil {
		releasesCopy = make([]go_pivnet.Release, len(releases))
		copy(releasesCopy, releases)
	}
	fake.productVersionsMutex.Lock()
	fake.productVersionsArgsForCall = append(fake.productVersionsArgsForCall, struct {
		productSlug string
		releases    []go_pivnet.Release
	}{productSlug, releasesCopy})
	fake.recordInvocation("ProductVersions", []interface{}{productSlug, releasesCopy})
	fake.productVersionsMutex.Unlock()
	if fake.ProductVersionsStub != nil {
		return fake.ProductVersionsStub(productSlug, releases)
	} else {
		return fake.productVersionsReturns.result1, fake.productVersionsReturns.result2
	}
}

func (fake *FakePivnetClient) ProductVersionsCallCount() int {
	fake.productVersionsMutex.RLock()
	defer fake.productVersionsMutex.RUnlock()
	return len(fake.productVersionsArgsForCall)
}

func (fake *FakePivnetClient) ProductVersionsArgsForCall(i int) (string, []go_pivnet.Release) {
	fake.productVersionsMutex.RLock()
	defer fake.productVersionsMutex.RUnlock()
	return fake.productVersionsArgsForCall[i].productSlug, fake.productVersionsArgsForCall[i].releases
}

func (fake *FakePivnetClient) ProductVersionsReturns(result1 []string, result2 error) {
	fake.ProductVersionsStub = nil
	fake.productVersionsReturns = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakePivnetClient) ReleaseETag(productSlug string, releaseID int) (string, error) {
	fake.releaseETagMutex.Lock()
	fake.releaseETagArgsForCall = append(fake.releaseETagArgsForCall, struct {
		productSlug string
		releaseID   int
	}{productSlug, releaseID})
	fake.recordInvocation("ReleaseETag", []interface{}{productSlug, releaseID})
	fake.releaseETagMutex.Unlock()
	if fake.ReleaseETagStub != nil {
		return fake.ReleaseETagStub(productSlug, releaseID)
	} else {
		return fake.releaseETagReturns.result1, fake.releaseETagReturns.result2
	}
}

func (fake *FakePivnetClient) ReleaseETagCallCount() int {
	fake.releaseETagMutex.RLock()
	defer fake.releaseETagMutex.RUnlock()
	return len(fake.releaseETagArgsForCall)
}

func (fake *FakePivnetClient) ReleaseETagArgsForCall(i int) (string, int) {
	fake.releaseETagMutex.RLock()
	defer fake.releaseETagMutex.RUnlock()
	return fake.releaseETagArgsForCall[i].productSlug, fake.releaseETagArgsForCall[i].releaseID
}

func (fake *FakePivnetClient) ReleaseETagReturns(result1 string, result2 error) {
	fake.ReleaseETagStub = nil
	fake.releaseETagReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakePivnetClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.releaseTypesMutex.RLock()
	defer fake.releaseTypesMutex.RUnlock()
	fake.releasesForProductSlugMutex.RLock()
	defer fake.releasesForProductSlugMutex.RUnlock()
	fake.productVersionsMutex.RLock()
	defer fake.productVersionsMutex.RUnlock()
	fake.releaseETagMutex.RLock()
	defer fake.releaseETagMutex.RUnlock()
	return fake.invocations
}

func (fake *FakePivnetClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
